language: generic

sudo: required

services:
  - docker

before_install:
  - docker build -t jessy2yon/docker-frontend-dev -f ./frontend/Dockerfile.dev ./frontend

script:
  - docker run -e CI=true jessy2yon/docker-frontend-dev npm run test

after_success:
  - docker build -t jessy2yon/docker-frontend ./frontend # 각각의 이미지 빌드
  - docker build -t jessy2yon/docker-backend ./backend
  - docker build -t jessy2yon/docker-nginx ./nginx

  - echo "$DOCKER_HUB_PASSWORD" | docker login -u "$DOCKER_HUB_ID" --password-stdin # 도커 허브에 로그인

  - docker push jessy2yon/docker-frontend # 빌드된 각각의 이미지들 도커 허브에 push
  - docker push jessy2yon/docker-backend
  - docker push jessy2yon/docker-nginx

deploy:
  provider: elasticbeanstalk
  region: "ap-northeast-2"
  app: "docker-fullstack-practice"
  env: "Dockerfullstackpractice-env"
  bucket_name: elasticbeanstalk-ap-northeast-2-344745973717
  bucket_path: "docker-fullstack-practice"
  on:
    branch: dev
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_ACCESS_KEY
